[2024-11-26T13:48:34.822+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_processing_dag_v2.fetch_model_data manual__2024-11-26T13:48:32.200563+00:00 [queued]>
[2024-11-26T13:48:34.831+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_processing_dag_v2.fetch_model_data manual__2024-11-26T13:48:32.200563+00:00 [queued]>
[2024-11-26T13:48:34.832+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-26T13:48:34.832+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-11-26T13:48:34.833+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-26T13:48:34.845+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fetch_model_data> on 2024-11-26 13:48:32.200563+00:00
[2024-11-26T13:48:34.852+0000] {standard_task_runner.py:55} INFO - Started process 67 to run task
[2024-11-26T13:48:34.855+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_processing_dag_v2', 'fetch_model_data', 'manual__2024-11-26T13:48:32.200563+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/data_download_dag.py', '--cfg-path', '/tmp/tmphoojgjmq']
[2024-11-26T13:48:34.858+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask fetch_model_data
[2024-11-26T13:48:34.914+0000] {task_command.py:388} INFO - Running <TaskInstance: data_processing_dag_v2.fetch_model_data manual__2024-11-26T13:48:32.200563+00:00 [running]> on host ceb20413ea9a
[2024-11-26T13:48:34.967+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_processing_dag_v2
AIRFLOW_CTX_TASK_ID=fetch_model_data
AIRFLOW_CTX_EXECUTION_DATE=2024-11-26T13:48:32.200563+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-26T13:48:32.200563+00:00
[2024-11-26T13:48:37.111+0000] {data_download_dag.py:32} ERROR - Nieoczekiwany błąd: Dane treningowe
[2024-11-26T13:48:37.114+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-11-26T13:48:37.123+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=data_processing_dag_v2, task_id=fetch_model_data, execution_date=20241126T134832, start_date=20241126T134834, end_date=20241126T134837
[2024-11-26T13:48:37.155+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-11-26T13:48:37.176+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
