[2024-11-26T13:09:37.874+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_1_data_split.download_data_from_google_sheets manual__2024-11-26T13:09:35.519917+00:00 [queued]>
[2024-11-26T13:09:37.881+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_1_data_split.download_data_from_google_sheets manual__2024-11-26T13:09:35.519917+00:00 [queued]>
[2024-11-26T13:09:37.882+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-26T13:09:37.882+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-11-26T13:09:37.882+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-26T13:09:37.904+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): download_data_from_google_sheets> on 2024-11-26 13:09:35.519917+00:00
[2024-11-26T13:09:37.911+0000] {standard_task_runner.py:55} INFO - Started process 95 to run task
[2024-11-26T13:09:37.913+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_1_data_split', 'download_data_from_google_sheets', 'manual__2024-11-26T13:09:35.519917+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/data_download_dag.py', '--cfg-path', '/tmp/tmpk74afqur']
[2024-11-26T13:09:37.916+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask download_data_from_google_sheets
[2024-11-26T13:09:37.973+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_1_data_split.download_data_from_google_sheets manual__2024-11-26T13:09:35.519917+00:00 [running]> on host 2de93360ae3c
[2024-11-26T13:09:38.044+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_1_data_split
AIRFLOW_CTX_TASK_ID=download_data_from_google_sheets
AIRFLOW_CTX_EXECUTION_DATE=2024-11-26T13:09:35.519917+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-26T13:09:35.519917+00:00
[2024-11-26T13:09:38.046+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_download_dag.py", line 18, in download_data_from_google_sheets
    creds = Credentials.from_service_account_file(json_path, scopes=scopes)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/oauth2/service_account.py", line 241, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/auth/_service_account_info.py", line 80, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'airflow-442316-8c5dfa0cf9c0.json'
[2024-11-26T13:09:38.058+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_1_data_split, task_id=download_data_from_google_sheets, execution_date=20241126T130935, start_date=20241126T130937, end_date=20241126T130938
[2024-11-26T13:09:38.074+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 13 for task download_data_from_google_sheets ([Errno 2] No such file or directory: 'airflow-442316-8c5dfa0cf9c0.json'; 95)
[2024-11-26T13:09:38.087+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-26T13:09:38.112+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
