[2024-11-26T14:09:35.490+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_split_google_sheets.split_data manual__2024-11-26T14:09:30.977878+00:00 [queued]>
[2024-11-26T14:09:35.499+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_split_google_sheets.split_data manual__2024-11-26T14:09:30.977878+00:00 [queued]>
[2024-11-26T14:09:35.500+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-26T14:09:35.501+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-11-26T14:09:35.501+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-26T14:09:35.516+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): split_data> on 2024-11-26 14:09:30.977878+00:00
[2024-11-26T14:09:35.524+0000] {standard_task_runner.py:55} INFO - Started process 81 to run task
[2024-11-26T14:09:35.527+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_split_google_sheets', 'split_data', 'manual__2024-11-26T14:09:30.977878+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/data_processing_dag.py', '--cfg-path', '/tmp/tmp90rb9d79']
[2024-11-26T14:09:35.529+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask split_data
[2024-11-26T14:09:35.585+0000] {task_command.py:388} INFO - Running <TaskInstance: data_split_google_sheets.split_data manual__2024-11-26T14:09:30.977878+00:00 [running]> on host 39b7a1eb8bf2
[2024-11-26T14:09:35.644+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_split_google_sheets
AIRFLOW_CTX_TASK_ID=split_data
AIRFLOW_CTX_EXECUTION_DATE=2024-11-26T14:09:30.977878+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-26T14:09:30.977878+00:00
[2024-11-26T14:09:35.657+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_processing_dag.py", line 34, in split_data
    data = pd.read_json(data_json)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 733, in read_json
    json_reader = JsonReader(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 818, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/json/_json.py", line 858, in _get_data_from_filepath
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 713, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 451, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2024-11-26T14:09:35.668+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=data_split_google_sheets, task_id=split_data, execution_date=20241126T140930, start_date=20241126T140935, end_date=20241126T140935
[2024-11-26T14:09:35.680+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 45 for task split_data (Invalid file path or buffer object type: <class 'NoneType'>; 81)
[2024-11-26T14:09:35.699+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-26T14:09:35.717+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
