[2024-11-28T17:48:38.757+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: 2_model_training_dag.train_model manual__2024-11-28T17:48:35.712297+00:00 [queued]>
[2024-11-28T17:48:38.771+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: 2_model_training_dag.train_model manual__2024-11-28T17:48:35.712297+00:00 [queued]>
[2024-11-28T17:48:38.771+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-28T17:48:38.771+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-11-28T17:48:38.772+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-28T17:48:38.787+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): train_model> on 2024-11-28 17:48:35.712297+00:00
[2024-11-28T17:48:38.800+0000] {standard_task_runner.py:55} INFO - Started process 98 to run task
[2024-11-28T17:48:38.839+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '2_model_training_dag', 'train_model', 'manual__2024-11-28T17:48:35.712297+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/2_model_training_dag.py', '--cfg-path', '/tmp/tmpvrp0m_ft']
[2024-11-28T17:48:38.879+0000] {standard_task_runner.py:83} INFO - Job 117: Subtask train_model
[2024-11-28T17:48:39.009+0000] {task_command.py:388} INFO - Running <TaskInstance: 2_model_training_dag.train_model manual__2024-11-28T17:48:35.712297+00:00 [running]> on host 9bd440fa5bc5
[2024-11-28T17:48:39.065+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=2_model_training_dag
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-11-28T17:48:35.712297+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-28T17:48:35.712297+00:00
[2024-11-28T17:48:39.260+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-11-28T17:48:45.189+0000] {python.py:177} INFO - Done. Returned value was: None
[2024-11-28T17:48:45.206+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=2_model_training_dag, task_id=train_model, execution_date=20241128T174835, start_date=20241128T174838, end_date=20241128T174845
[2024-11-28T17:48:45.296+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-11-28T17:48:45.309+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
