[2024-11-26T13:53:23.940+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_processing_dag_v2.standardize_and_normalize_data manual__2024-11-26T13:53:14.334430+00:00 [queued]>
[2024-11-26T13:53:23.946+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_processing_dag_v2.standardize_and_normalize_data manual__2024-11-26T13:53:14.334430+00:00 [queued]>
[2024-11-26T13:53:23.947+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-26T13:53:23.947+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-11-26T13:53:23.947+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-26T13:53:23.959+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): standardize_and_normalize_data> on 2024-11-26 13:53:14.334430+00:00
[2024-11-26T13:53:23.966+0000] {standard_task_runner.py:55} INFO - Started process 95 to run task
[2024-11-26T13:53:23.968+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_processing_dag_v2', 'standardize_and_normalize_data', 'manual__2024-11-26T13:53:14.334430+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/data_download_dag.py', '--cfg-path', '/tmp/tmpimhfeq7k']
[2024-11-26T13:53:23.970+0000] {standard_task_runner.py:83} INFO - Job 38: Subtask standardize_and_normalize_data
[2024-11-26T13:53:24.017+0000] {task_command.py:388} INFO - Running <TaskInstance: data_processing_dag_v2.standardize_and_normalize_data manual__2024-11-26T13:53:14.334430+00:00 [running]> on host 5def5bffc4a2
[2024-11-26T13:53:24.076+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_processing_dag_v2
AIRFLOW_CTX_TASK_ID=standardize_and_normalize_data
AIRFLOW_CTX_EXECUTION_DATE=2024-11-26T13:53:14.334430+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-26T13:53:14.334430+00:00
[2024-11-26T13:53:24.105+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_download_dag.py", line 54, in standardize_and_normalize_data
    data_scaled = scaler.fit_transform(data.select_dtypes(include=['float64', 'int64']))
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/base.py", line 916, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 839, in fit
    return self.partial_fit(X, y, sample_weight)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 875, in partial_fit
    X = self._validate_data(
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/base.py", line 605, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "/home/airflow/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 795, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
  File "<__array_function__ internals>", line 180, in result_type
ValueError: at least one array or dtype is required
[2024-11-26T13:53:24.119+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=data_processing_dag_v2, task_id=standardize_and_normalize_data, execution_date=20241126T135314, start_date=20241126T135323, end_date=20241126T135324
[2024-11-26T13:53:24.136+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 38 for task standardize_and_normalize_data (at least one array or dtype is required; 95)
[2024-11-26T13:53:24.181+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-26T13:53:24.210+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
